services:
  - type: web
    name: garantia-lenovo-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 app:app"
    buildPacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
      - url: https://github.com/heroku/heroku-buildpack-chromedriver
