services:
  - type: web
    name: garantia-lenovo-app
    env: docker
    startCommand: "gunicorn --worker-class gevent --bind 0.0.0.0:10000 app:app"
    envVars:
      - key: RUNNING_IN_RENDER
        value: "true"