services:
  - type: web
    name: garantia-lenovo-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 app:app"
    envVars:
      - key: RUNNING_IN_RENDER
        value: "true"
    buildPacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
      - url: https://github.com/heroku/heroku-buildpack-chromedriver
