services:
  - type: web
    name: garantia-lenovo-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 app:app"
    envVars:
      - key: RUNNING_IN_RENDER
        value: "true"
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
    buildPacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
      - url: https://github.com/heroku/heroku-buildpack-chromedriver
